{"name": "test_del_object", "status": "failed", "statusDetails": {"message": "AssertionError: Object name wasn't created.", "trace": "create_new_obj_endpoint = <endpoints.create_obj.CreateObject object at 0x000001E32B5218E0>\n\n    @pytest.fixture()\n    def create_obj(create_new_obj_endpoint):\n        body = {\n            \"name\": f\"New_obj_{random.randint}\",\n            \"data\": {\n                \"year\": 1982,\n                \"price\": 2805.99,\n                \"CPU model\": \"Intel Core i9DKA\",\n                \"Hard disk size\": \"1 TB DKA\"\n            }\n        }\n        create_new_obj_endpoint.create_new_obj(body)\n>       create_new_obj_endpoint.check_obj_name(\"name\")\n\nconftest.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <endpoints.create_obj.CreateObject object at 0x000001E32B5218E0>, name = 'name'\n\n    @allure.step('Проверяем имя созданного объекта.')\n    def check_obj_name(self, name):\n>       assert self.obj_json['name'] == name, f\"Object {name} wasn't created.\"\nE       AssertionError: Object name wasn't created.\n\nendpoints\\create_obj.py:23: AssertionError"}, "start": 1713416133235, "stop": 1713416133235, "uuid": "090c7e93-bdcb-4302-802a-e94297aacbc6", "historyId": "b8640b4770c956bbc4503561a13fd915", "testCaseId": "b8640b4770c956bbc4503561a13fd915", "fullName": "tests.test_some_app#test_del_object", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_some_app"}, {"name": "host", "value": "Kirill"}, {"name": "thread", "value": "6048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_some_app"}]}