{"name": "test_change_object_patch", "status": "failed", "statusDetails": {"message": "AssertionError: Object {'name'} wasn't created.", "trace": "create_new_obj_endpoint = <endpoints.create_obj.CreateObject object at 0x000002E541A52C00>\n\n    @pytest.fixture()\n    def create_obj(create_new_obj_endpoint):\n        body = {\n            \"name\": \"New_obj_DKA2805\",\n            \"data\": {\n                \"year\": 1982,\n                \"price\": 2805.99,\n                \"CPU model\": \"Intel Core i9DKA\",\n                \"Hard disk size\": \"1 TB DKA\"\n            }\n        }\n        create_new_obj_endpoint.create_new_obj(body)\n>       create_new_obj_endpoint.check_obj_name({\"name\"})\n\nconftest.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <endpoints.create_obj.CreateObject object at 0x000002E541A52C00>, name = {'name'}\n\n    @allure.step('Проверяем имя созданного объекта.')\n    def check_obj_name(self, name):\n>       assert self.obj_json['name'] == name, f\"Object {name} wasn't created.\"\nE       AssertionError: Object {'name'} wasn't created.\n\nendpoints\\create_obj.py:23: AssertionError"}, "start": 1713417424634, "stop": 1713417424634, "uuid": "bcdb48a9-bf0e-4fc1-b35b-bbe93e86d493", "historyId": "ef1dd2a191ecbf4bf6ce7dbdb7c44bd9", "testCaseId": "ef1dd2a191ecbf4bf6ce7dbdb7c44bd9", "fullName": "tests.test_some_app#test_change_object_patch", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_some_app"}, {"name": "host", "value": "Kirill"}, {"name": "thread", "value": "4324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_some_app"}]}