{"uuid": "08b620cb-b01f-4f8b-a257-b3f704f2629b", "children": ["fdb556d6-c232-491e-ab21-91d789a7267f"], "befores": [{"name": "create_obj", "status": "failed", "statusDetails": {"message": "AssertionError: Object {'name': 'New_obj_<bound method Random.randint of <random.Random object at 0x000001F7E5607690>>', 'data': {'year': 1982, 'price': 2805.99, 'CPU model': 'Intel Core i9DKA', 'Hard disk size': '1 TB DKA'}} wasn't created.\n", "trace": "  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\test_api_dka\\conftest.py\", line 41, in create_obj\n    create_new_obj_endpoint.check_obj_name(body)\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\test_api_dka\\endpoints\\create_obj.py\", line 23, in check_obj_name\n    assert self.obj_json['name'] == name, f\"Object {name} wasn't created.\"\n"}, "steps": [{"name": "Создаем новый объект.", "status": "passed", "parameters": [{"name": "body", "value": "{'name': 'New_obj_<bound method Random.randint of <random.Random object at 0x000001F7E5607690>>', 'data': {'year': 1982, 'price': 2805.99, 'CPU model': 'Intel Core i9DKA', 'Hard disk size': '1 TB DKA'}}"}], "start": 1713416015225, "stop": 1713416016505}, {"name": "Проверяем имя созданного объекта.", "status": "failed", "statusDetails": {"message": "AssertionError: Object {'name': 'New_obj_<bound method Random.randint of <random.Random object at 0x000001F7E5607690>>', 'data': {'year': 1982, 'price': 2805.99, 'CPU model': 'Intel Core i9DKA', 'Hard disk size': '1 TB DKA'}} wasn't created.\n", "trace": "  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\test_api_dka\\endpoints\\create_obj.py\", line 23, in check_obj_name\n    assert self.obj_json['name'] == name, f\"Object {name} wasn't created.\"\n"}, "parameters": [{"name": "name", "value": "{'name': 'New_obj_<bound method Random.randint of <random.Random object at 0x000001F7E5607690>>', 'data': {'year': 1982, 'price': 2805.99, 'CPU model': 'Intel Core i9DKA', 'Hard disk size': '1 TB DKA'}}"}], "start": 1713416016505, "stop": 1713416016505}], "start": 1713416015225, "stop": 1713416016505}], "start": 1713416015225, "stop": 1713416016515}